# Generated by Django 5.1.2 on 2024-10-17 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="course",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="updated_at",
            new_name="updated",
        ),
    ]
