# Generated by Django 5.1.2 on 2024-10-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
        ("school", "0004_alter_course_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="teacher",
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="core.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="school.department",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="core.teacher",
            ),
        ),
    ]
